//! Ephemeral process execution layer and control plane synchronization boundary.

use std::os::unix::io::{AsRawFd, FromRawFd, OwnedFd, RawFd};
use nix::sys::signal::{sigaction, SaFlags, SigAction, SigHandler, SigSet, Signal};
use nix::sys::wait::{waitpid, WaitStatus};
use nix::unistd::Pid;
use crate::error::{BoundaryExitStatus, IsolationError};
use crate::isolation::mount::{mount_ephemeral_tmpfs, set_mount_propagation_private, MountConfig};
use crate::isolation::namespace::NamespaceFlags;
use crate::isolation::seccomp::SeccompFilter;

const STACK_SIZE: usize = 2 * 1024 * 1024; // 2MB stack for cloned execution layer

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ViolationPacket {
    pub syscall_nr: u32,
    pub instruction_pointer: u64,
}

// Global raw descriptor for the isolated child's SIGSYS handler
static mut CHILD_SYNC_FD: RawFd = -1;

/// Signal handler intercepting SIGSYS generated by SECCOMP_RET_TRAP.
extern "C" fn sigsys_handler(
    _sig: libc::c_int,
    info: *mut libc::siginfo_t,
    _ucontext: *mut libc::c_void,
) {
    if !info.is_null() {
        let (syscall_nr, ip) = unsafe {
            // In Linux siginfo_t, si_syscall and si_call_addr are fields for SIGSYS
            let siginfo = &*info;
            let syscall_nr = libc_siginfo_syscall(siginfo);
            let ip = libc_siginfo_call_addr(siginfo) as u64;
            (syscall_nr, ip)
        };

        let packet = ViolationPacket {
            syscall_nr,
            instruction_pointer: ip,
        };

        unsafe {
            if CHILD_SYNC_FD >= 0 {
                let bytes = std::slice::from_raw_parts(
                    &packet as *const ViolationPacket as *const u8,
                    std::mem::size_of::<ViolationPacket>(),
                );
                let _ = libc::write(CHILD_SYNC_FD, bytes.as_ptr() as *const libc::c_void, bytes.len());
            }
            libc::_exit(128 + libc::SIGSYS);
        }
    } else {
        unsafe { libc::_exit(128 + libc::SIGSYS) };
    }
}

#[cfg(target_arch = "x86_64")]
unsafe fn libc_siginfo_syscall(info: &libc::siginfo_t) -> u32 {
    // In glibc / musl x86_64 siginfo_t, si_syscall is located at offset 0x20
    let ptr = (info as *const libc::siginfo_t as *const u8).add(32) as *const i32;
    *ptr as u32
}

#[cfg(target_arch = "aarch64")]
unsafe fn libc_siginfo_syscall(info: &libc::siginfo_t) -> u32 {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(24) as *const i32;
    *ptr as u32
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
unsafe fn libc_siginfo_syscall(_info: &libc::siginfo_t) -> u32 {
    0
}

#[cfg(target_arch = "x86_64")]
unsafe fn libc_siginfo_call_addr(info: &libc::siginfo_t) -> *mut libc::c_void {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(16) as *const *mut libc::c_void;
    *ptr
}

#[cfg(target_arch = "aarch64")]
unsafe fn libc_siginfo_call_addr(info: &libc::siginfo_t) -> *mut libc::c_void {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(16) as *const *mut libc::c_void;
    *ptr
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
unsafe fn libc_siginfo_call_addr(_info: &libc::siginfo_t) -> *mut libc::c_void {
    std::ptr::null_mut()
}

/// Execution configuration governing the ephemeral process boundary.
#[derive(Debug, Clone)]
pub struct ProcessBoundaryConfig {
    pub namespaces: NamespaceFlags,
    pub mount_config: MountConfig,
    pub seccomp_filter: SeccompFilter,
}

impl Default for ProcessBoundaryConfig {
    fn default() -> Self {
        Self {
            namespaces: NamespaceFlags::default(),
            mount_config: MountConfig::default(),
            seccomp_filter: SeccompFilter::default().with_baseline_whitelist(),
        }
    }
}

/// Clones an ephemeral process into isolated namespaces, applies boundaries, and executes action.
pub fn execute_isolated_process<F, R>(
    config: &ProcessBoundaryConfig,
    action: F,
) -> Result<(BoundaryExitStatus, Option<R>), IsolationError>
where
    F: FnOnce() -> R + Send + 'static,
    R: Send + 'static,
{
    // Create synchronization socketpair for parent-child boundary coordination
    let mut fds = [0; 2];
    let res = unsafe {
        libc::socketpair(
            libc::AF_UNIX,
            libc::SOCK_STREAM | libc::SOCK_CLOEXEC,
            0,
            fds.as_mut_ptr(),
        )
    };
    if res != 0 {
        return Err(IsolationError::SyncError(format!(
            "Failed to create socketpair: errno {}",
            std::io::Error::last_os_error()
        )));
    }

    let parent_sock = unsafe { OwnedFd::from_raw_fd(fds[0]) };
    let child_sock = unsafe { OwnedFd::from_raw_fd(fds[1]) };

    // Allocate isolated stack for clone(2)
    let mut stack = vec![0u8; STACK_SIZE];
    let stack_top = unsafe { (stack.as_mut_ptr() as *mut u8).add(STACK_SIZE) };

    // Pack execution closure and config into box for raw pointer handover
    struct ChildPayload<F> {
        config: ProcessBoundaryConfig,
        child_sock: OwnedFd,
        action: Option<F>,
    }

    let payload = Box::new(ChildPayload {
        config: config.clone(),
        child_sock,
        action: Some(action),
    });
    let payload_ptr = Box::into_raw(payload);

    extern "C" fn child_entry_point<F, R>(arg: *mut libc::c_void) -> libc::c_int
    where
        F: FnOnce() -> R + Send + 'static,
        R: Send + 'static,
    {
        let mut payload = unsafe { Box::from_raw(arg as *mut ChildPayload<F>) };
        let child_fd = payload.child_sock.as_raw_fd();
        unsafe {
            CHILD_SYNC_FD = child_fd;
        }

        // Install SIGSYS signal handler for deterministic syscall interception
        let sa = SigAction::new(
            SigHandler::SigAction(sigsys_handler),
            SaFlags::SA_SIGINFO | SaFlags::SA_NODEFER,
            SigSet::empty(),
        );
        let _ = unsafe { sigaction(Signal::SIGSYS, &sa) };

        // 1. Mount boundary setup
        if payload.config.namespaces.contains(NamespaceFlags::MOUNT) {
            let _ = set_mount_propagation_private();
            let _ = mount_ephemeral_tmpfs(&payload.config.mount_config.tmpfs_path);
        }

        // 2. Notify parent control plane: child ready for baseline reset
        let ready_byte: [u8; 1] = [1];
        let _ = unsafe {
            libc::write(
                child_fd,
                ready_byte.as_ptr() as *const libc::c_void,
                1,
            )
        };

        // 3. Await parent acknowledgment (baseline clear completion)
        let mut ack_byte = [0u8; 1];
        let n = unsafe {
            libc::read(
                child_fd,
                ack_byte.as_mut_ptr() as *mut libc::c_void,
                1,
            )
        };
        if n <= 0 {
            unsafe { libc::_exit(1) };
        }

        // 4. Attach Seccomp-BPF syscall interception boundary
        if let Err(_e) = payload.config.seccomp_filter.attach() {
            unsafe { libc::_exit(2) };
        }

        // 5. Execute isolated state-mutation action
        if let Some(act) = payload.action.take() {
            let _ = act();
        }

        // 6. Signal completion to parent
        let done_byte: [u8; 1] = [0];
        let _ = unsafe {
            libc::write(
                child_fd,
                done_byte.as_ptr() as *const libc::c_void,
                1,
            )
        };

        unsafe { libc::_exit(0) };
    }

    let clone_flags = config.namespaces.to_clone_flags().bits() | libc::SIGCHLD;

    let child_pid = unsafe {
        libc::clone(
            std::mem::transmute(child_entry_point::<F, R> as *const ()),
            stack_top as *mut libc::c_void,
            clone_flags,
            payload_ptr as *mut libc::c_void,
        )
    };

    if child_pid < 0 {
        return Err(IsolationError::ProcessFailure(format!(
            "Failed to clone execution layer: errno {}",
            std::io::Error::last_os_error()
        )));
    }

    let pid = Pid::from_raw(child_pid);

    // Coordinate with child across synchronization boundary
    // Await child readiness byte
    let mut ready_buf = [0u8; 1];
    let n = unsafe {
        libc::read(
            parent_sock.as_raw_fd(),
            ready_buf.as_mut_ptr() as *mut libc::c_void,
            1,
        )
    };

    if n > 0 {
        // Reset kernel page-table tracking for child: write "4\n" to /proc/[pid]/clear_refs
        let clear_refs_path = format!("/proc/{}/clear_refs", child_pid);
        if let Ok(mut file) = std::fs::File::create(&clear_refs_path) {
            use std::io::Write;
            let _ = file.write_all(b"4\n");
        }

        // Send ACK byte to release child into action execution
        let ack_byte = [1u8; 1];
        let _ = unsafe {
            libc::write(
                parent_sock.as_raw_fd(),
                ack_byte.as_ptr() as *const libc::c_void,
                1,
            )
        };
    }

    // Wait for child process termination
    let wait_status = waitpid(pid, None).map_err(|e| {
        IsolationError::ProcessFailure(format!("waitpid failure on child {child_pid}: {e}"))
    })?;

    // Check if child sent a ViolationPacket across the synchronization socket
    let mut packet = ViolationPacket {
        syscall_nr: 0,
        instruction_pointer: 0,
    };
    let packet_size = std::mem::size_of::<ViolationPacket>();
    let packet_bytes = unsafe {
        std::slice::from_raw_parts_mut(
            &mut packet as *mut ViolationPacket as *mut u8,
            packet_size,
        )
    };

    let n = unsafe {
        libc::read(
            parent_sock.as_raw_fd(),
            packet_bytes.as_mut_ptr() as *mut libc::c_void,
            packet_size,
        )
    };

    let boundary_status = if n == packet_size as isize && packet.syscall_nr != 0 {
        BoundaryExitStatus::SyscallViolation {
            syscall_nr: packet.syscall_nr,
            instruction_pointer: packet.instruction_pointer,
        }
    } else {
        match wait_status {
            WaitStatus::Exited(_, code) => BoundaryExitStatus::Exited(code),
            WaitStatus::Signaled(_, sig, _) => {
                if sig == Signal::SIGSYS {
                    BoundaryExitStatus::SyscallViolation {
                        syscall_nr: 0,
                        instruction_pointer: 0,
                    }
                } else {
                    BoundaryExitStatus::Signaled(sig as i32)
                }
            }
            _ => BoundaryExitStatus::Exited(-1),
        }
    };

    Ok((boundary_status, None))
}
