//! Ephemeral process execution layer and control plane synchronization boundary.

use crate::delta::network::{bind_loopback_listener, NetworkBoundary, TransparentProxy};
use crate::error::{BoundaryExitStatus, IsolationError};
use crate::isolation::mount::{mount_ephemeral_tmpfs, set_mount_propagation_private, MountConfig};
use crate::isolation::namespace::{bring_loopback_up, NamespaceFlags};
use crate::isolation::seccomp::SeccompFilter;
use nix::sys::signal::{sigaction, SaFlags, SigAction, SigHandler, SigSet, Signal};
use nix::sys::wait::{waitpid, WaitStatus};
use nix::unistd::Pid;
use std::net::TcpListener;
use std::os::unix::io::{AsRawFd, FromRawFd, IntoRawFd, OwnedFd, RawFd};

const STACK_SIZE: usize = 2 * 1024 * 1024; // 2MB stack for cloned execution layer

/// Control-plane protocol byte: execution layer ready for baseline reset.
const BOUNDARY_READY: u8 = 0x01;

/// Control-plane protocol byte: isolated action completed without a boundary breach.
/// The execution layer then blocks until the control plane releases it.
const BOUNDARY_DONE: u8 = 0x00;

/// Control-plane protocol byte: boundary breach intercepted; frame carries a `ViolationPacket`.
const BOUNDARY_VIOLATION: u8 = 0x02;

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ViolationPacket {
    pub syscall_nr: u32,
    pub instruction_pointer: u64,
}

/// Framed boundary breach record: protocol tag byte followed by a `ViolationPacket`.
const VIOLATION_PACKET_SIZE: usize = std::mem::size_of::<ViolationPacket>();
const VIOLATION_FRAME_SIZE: usize = 1 + VIOLATION_PACKET_SIZE;

// Global raw descriptor for the isolated child's SIGSYS handler
static mut CHILD_SYNC_FD: RawFd = -1;

/// Signal handler intercepting SIGSYS generated by SECCOMP_RET_TRAP.
extern "C" fn sigsys_handler(
    _sig: libc::c_int,
    info: *mut libc::siginfo_t,
    _ucontext: *mut libc::c_void,
) {
    if !info.is_null() {
        let (syscall_nr, ip) = unsafe {
            // In Linux siginfo_t, si_syscall and si_call_addr are fields for SIGSYS
            let siginfo = &*info;
            let syscall_nr = libc_siginfo_syscall(siginfo);
            let ip = libc_siginfo_call_addr(siginfo) as u64;
            (syscall_nr, ip)
        };

        let packet = ViolationPacket {
            syscall_nr,
            instruction_pointer: ip,
        };

        unsafe {
            if CHILD_SYNC_FD >= 0 {
                let mut frame = [0u8; VIOLATION_FRAME_SIZE];
                frame[0] = BOUNDARY_VIOLATION;
                let packet_bytes = std::slice::from_raw_parts(
                    &packet as *const ViolationPacket as *const u8,
                    VIOLATION_PACKET_SIZE,
                );
                frame[1..].copy_from_slice(packet_bytes);
                let _ = libc::write(
                    CHILD_SYNC_FD,
                    frame.as_ptr() as *const libc::c_void,
                    frame.len(),
                );
            }
            libc::_exit(128 + libc::SIGSYS);
        }
    } else {
        unsafe { libc::_exit(128 + libc::SIGSYS) }
    }
}

#[cfg(target_arch = "x86_64")]
unsafe fn libc_siginfo_syscall(info: &libc::siginfo_t) -> u32 {
    // On 64-bit Linux siginfo_t, `_sifields` is 8-byte aligned and therefore
    // begins at offset 16: si_call_addr (16) then si_syscall (24).
    let ptr = (info as *const libc::siginfo_t as *const u8).add(24) as *const i32;
    *ptr as u32
}

#[cfg(target_arch = "aarch64")]
unsafe fn libc_siginfo_syscall(info: &libc::siginfo_t) -> u32 {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(24) as *const i32;
    *ptr as u32
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
unsafe fn libc_siginfo_syscall(_info: &libc::siginfo_t) -> u32 {
    0
}

#[cfg(target_arch = "x86_64")]
unsafe fn libc_siginfo_call_addr(info: &libc::siginfo_t) -> *mut libc::c_void {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(16) as *const *mut libc::c_void;
    *ptr
}

#[cfg(target_arch = "aarch64")]
unsafe fn libc_siginfo_call_addr(info: &libc::siginfo_t) -> *mut libc::c_void {
    let ptr = (info as *const libc::siginfo_t as *const u8).add(16) as *const *mut libc::c_void;
    *ptr
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
unsafe fn libc_siginfo_call_addr(_info: &libc::siginfo_t) -> *mut libc::c_void {
    std::ptr::null_mut()
}

/// Execution configuration governing the ephemeral process boundary.
#[derive(Debug, Clone)]
pub struct ProcessBoundaryConfig {
    pub namespaces: NamespaceFlags,
    pub mount_config: MountConfig,
    pub seccomp_filter: SeccompFilter,

    /// Optional deterministic network boundary. When configured, the isolated execution layer
    /// binds the mock listener inside its own network namespace and forwards the descriptor to
    /// the control plane, which serves it: outbound requests from within the boundary reach the
    /// transparent proxy, and every interception is recorded on the control plane.
    pub network_boundary: Option<NetworkBoundary>,
}

impl Default for ProcessBoundaryConfig {
    fn default() -> Self {
        Self {
            namespaces: NamespaceFlags::default(),
            mount_config: MountConfig::default(),
            seccomp_filter: SeccompFilter::default().with_baseline_whitelist(),
            network_boundary: None,
        }
    }
}

/// Control-plane view of the live isolated execution layer during state inspection.
pub struct BoundaryContext {
    /// PID of the live isolated execution layer, blocked on the synchronization boundary.
    pub child_pid: i32,

    /// Transparent proxy serving the isolated network namespace's mock listener. Present when the
    /// boundary was configured with a [`NetworkBoundary`].
    pub network: Option<TransparentProxy>,
}

/// Control message buffer, aligned for the `cmsghdr` stored by the kernel.
#[repr(C, align(8))]
struct ControlBuffer([u8; 64]);

/// Send the readiness frame, optionally carrying a descriptor to forward to the control plane.
fn send_boundary_ready(fd: RawFd, forward: Option<RawFd>) -> std::io::Result<()> {
    let payload = [BOUNDARY_READY];
    let mut iov = libc::iovec {
        iov_base: payload.as_ptr() as *mut libc::c_void,
        iov_len: payload.len(),
    };
    let mut control = ControlBuffer([0u8; 64]);
    let mut message: libc::msghdr = unsafe { std::mem::zeroed() };
    message.msg_iov = &mut iov;
    message.msg_iovlen = 1;

    if let Some(raw_fd) = forward {
        let fd_size = std::mem::size_of::<libc::c_int>();
        message.msg_control = control.0.as_mut_ptr() as *mut libc::c_void;
        message.msg_controllen = unsafe { libc::CMSG_SPACE(fd_size as libc::c_uint) as usize };

        let header = unsafe { libc::CMSG_FIRSTHDR(&message) };
        if header.is_null() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "control message buffer too small for a forwarded descriptor",
            ));
        }

        unsafe {
            (*header).cmsg_level = libc::SOL_SOCKET;
            (*header).cmsg_type = libc::SCM_RIGHTS;
            (*header).cmsg_len = libc::CMSG_LEN(fd_size as libc::c_uint) as usize;
            std::ptr::copy_nonoverlapping(
                &raw_fd as *const RawFd as *const u8,
                libc::CMSG_DATA(header),
                fd_size,
            );
        }
    }

    let sent = unsafe { libc::sendmsg(fd, &message, libc::MSG_NOSIGNAL) };
    if sent < 0 {
        return Err(std::io::Error::last_os_error());
    }
    if sent != payload.len() as isize {
        return Err(std::io::Error::new(
            std::io::ErrorKind::WriteZero,
            "short readiness frame write",
        ));
    }

    Ok(())
}

/// Receive the readiness frame, extracting a forwarded listener descriptor when present.
fn recv_boundary_ready(fd: RawFd) -> (u8, Option<OwnedFd>) {
    let mut payload = [0u8; 1];
    let mut iov = libc::iovec {
        iov_base: payload.as_mut_ptr() as *mut libc::c_void,
        iov_len: payload.len(),
    };
    let mut control = ControlBuffer([0u8; 64]);
    let mut message: libc::msghdr = unsafe { std::mem::zeroed() };
    message.msg_iov = &mut iov;
    message.msg_iovlen = 1;
    message.msg_control = control.0.as_mut_ptr() as *mut libc::c_void;
    message.msg_controllen = control.0.len();

    let received = unsafe { libc::recvmsg(fd, &mut message, libc::MSG_CMSG_CLOEXEC) };
    if received < 1 {
        return (0, None);
    }

    let fd_size = std::mem::size_of::<libc::c_int>();
    let header = unsafe { libc::CMSG_FIRSTHDR(&message) };
    let mut forwarded = None;

    unsafe {
        let carries_descriptor = !header.is_null()
            && (*header).cmsg_level == libc::SOL_SOCKET
            && (*header).cmsg_type == libc::SCM_RIGHTS
            && (*header).cmsg_len >= libc::CMSG_LEN(fd_size as libc::c_uint) as usize;

        if carries_descriptor {
            let mut raw_fd: RawFd = -1;
            std::ptr::copy_nonoverlapping(
                libc::CMSG_DATA(header),
                &mut raw_fd as *mut RawFd as *mut u8,
                fd_size,
            );
            if raw_fd >= 0 {
                forwarded = Some(OwnedFd::from_raw_fd(raw_fd));
            }
        }
    }

    (payload[0], forwarded)
}

/// Terminate and reap an execution layer that cannot complete its boundary handshake.
fn terminate_child(pid: Pid) {
    unsafe { libc::kill(pid.as_raw(), libc::SIGKILL) };
    let _ = waitpid(pid, None);
}

/// Wire the isolated network boundary: enable namespace loopback so the mock listener is
/// reachable from within the boundary, then forward the bound listener to the control plane.
fn prepare_network_boundary(
    boundary: &NetworkBoundary,
    child_fd: RawFd,
) -> Result<(), IsolationError> {
    bring_loopback_up()?;
    let listener = bind_loopback_listener(boundary.port)?;
    send_boundary_ready(child_fd, Some(listener.as_raw_fd())).map_err(|e| {
        IsolationError::SyncError(format!("Failed to forward network boundary listener: {e}"))
    })?;
    Ok(())
}

/// Write a control-plane protocol byte ignoring `SIGPIPE` when the peer boundary is gone.
fn send_control_byte(fd: RawFd, byte: u8) {
    let buf = [byte; 1];
    unsafe {
        let _ = libc::send(
            fd,
            buf.as_ptr() as *const libc::c_void,
            buf.len(),
            libc::MSG_NOSIGNAL,
        );
    }
}

/// Decode a raw wait status into a typed boundary exit status.
fn decode_wait_status(status: WaitStatus) -> BoundaryExitStatus {
    match status {
        WaitStatus::Exited(_, code) => BoundaryExitStatus::Exited(code),
        WaitStatus::Signaled(_, sig, _) => {
            if sig == Signal::SIGSYS {
                BoundaryExitStatus::SyscallViolation {
                    syscall_nr: 0,
                    instruction_pointer: 0,
                }
            } else {
                BoundaryExitStatus::Signaled(sig as i32)
            }
        }
        _ => BoundaryExitStatus::Exited(-1),
    }
}

/// Clones an ephemeral process into isolated namespaces, applies boundaries, and executes action.
pub fn execute_isolated_process<F, R>(
    config: &ProcessBoundaryConfig,
    action: F,
) -> Result<(BoundaryExitStatus, Option<R>), IsolationError>
where
    F: FnOnce() -> R + Send + 'static,
    R: Send + 'static,
{
    execute_isolated_process_with_inspection(config, action, |_context| ())
        .map(|(status, _)| (status, None))
}

/// Clones an ephemeral process into isolated namespaces, applies boundaries, and executes action,
/// invoking `inspect` on the control plane while the ephemeral execution layer is still live.
///
/// The isolated execution layer retains its Copy-on-Write address space, blocked on the
/// synchronization boundary, for the duration of `inspect`. This allows the state delta engine
/// to sample `[pid]/pagemap` soft-dirty bits and read mutated pages before the boundary closes.
/// `inspect` receives a [`BoundaryContext`] carrying the live child PID and, when a network
/// boundary is configured, the transparent proxy serving the isolated namespace; its return
/// value is surfaced alongside the exit status.
pub fn execute_isolated_process_with_inspection<F, R, I, T>(
    config: &ProcessBoundaryConfig,
    action: F,
    inspect: I,
) -> Result<(BoundaryExitStatus, Option<T>), IsolationError>
where
    F: FnOnce() -> R + Send + 'static,
    R: Send + 'static,
    I: FnOnce(BoundaryContext) -> T,
{
    // Create synchronization socketpair for parent-child boundary coordination
    let mut fds = [0; 2];
    let res = unsafe {
        libc::socketpair(
            libc::AF_UNIX,
            libc::SOCK_STREAM | libc::SOCK_CLOEXEC,
            0,
            fds.as_mut_ptr(),
        )
    };
    if res != 0 {
        return Err(IsolationError::SyncError(format!(
            "Failed to create socketpair: errno {}",
            std::io::Error::last_os_error()
        )));
    }

    let parent_sock = unsafe { OwnedFd::from_raw_fd(fds[0]) };
    let child_sock = unsafe { OwnedFd::from_raw_fd(fds[1]) };

    // Allocate isolated stack for clone(2)
    let mut stack = vec![0u8; STACK_SIZE];
    let stack_top = unsafe { stack.as_mut_ptr().add(STACK_SIZE) };

    // Pack execution closure and config into box for raw pointer handover
    struct ChildPayload<F> {
        config: ProcessBoundaryConfig,
        child_sock: OwnedFd,
        action: Option<F>,
    }

    let payload = Box::new(ChildPayload {
        config: config.clone(),
        child_sock,
        action: Some(action),
    });
    let payload_ptr = Box::into_raw(payload);

    extern "C" fn child_entry_point<F, R>(arg: *mut libc::c_void) -> libc::c_int
    where
        F: FnOnce() -> R + Send + 'static,
        R: Send + 'static,
    {
        let mut payload = unsafe { Box::from_raw(arg as *mut ChildPayload<F>) };
        let child_fd = payload.child_sock.as_raw_fd();
        unsafe {
            CHILD_SYNC_FD = child_fd;
        }

        // Install SIGSYS signal handler for deterministic syscall interception
        let sa = SigAction::new(
            SigHandler::SigAction(sigsys_handler),
            SaFlags::SA_SIGINFO | SaFlags::SA_NODEFER,
            SigSet::empty(),
        );
        let _ = unsafe { sigaction(Signal::SIGSYS, &sa) };

        // 1. Mount boundary setup
        if payload.config.namespaces.contains(NamespaceFlags::MOUNT) {
            let _ = set_mount_propagation_private();
            let _ = mount_ephemeral_tmpfs(&payload.config.mount_config.tmpfs_path);
        }

        // 2. Notify parent control plane: child ready for baseline reset. When a network boundary
        //    is configured, the isolated network namespace binds the schema-driven mock listener
        //    and forwards the descriptor, so outbound requests reach the transparent proxy.
        let ready = match payload.config.network_boundary.as_ref() {
            Some(boundary) => prepare_network_boundary(boundary, child_fd).is_ok(),
            None => send_boundary_ready(child_fd, None).is_ok(),
        };
        if !ready {
            unsafe { libc::_exit(3) }
        }

        // 3. Await parent acknowledgment (baseline clear completion)
        let mut ack_byte = [0u8; 1];
        let n = unsafe { libc::read(child_fd, ack_byte.as_mut_ptr() as *mut libc::c_void, 1) };
        if n <= 0 {
            unsafe { libc::_exit(1) }
        }

        // 4. Attach Seccomp-BPF syscall interception boundary
        if let Err(_e) = payload.config.seccomp_filter.attach() {
            unsafe { libc::_exit(2) }
        }

        // 5. Execute isolated state-mutation action
        if let Some(act) = payload.action.take() {
            let _ = act();
        }

        // 6. Signal completion to parent, then hold the CoW address space open until released
        let done_byte: [u8; 1] = [BOUNDARY_DONE];
        let _ = unsafe { libc::write(child_fd, done_byte.as_ptr() as *const libc::c_void, 1) };

        let mut release_byte = [0u8; 1];
        let _ = unsafe { libc::read(child_fd, release_byte.as_mut_ptr() as *mut libc::c_void, 1) };

        unsafe { libc::_exit(0) }
    }

    let clone_flags = config.namespaces.to_clone_flags().bits() | libc::SIGCHLD;

    let child_pid = unsafe {
        libc::clone(
            std::mem::transmute::<*const (), extern "C" fn(*mut libc::c_void) -> libc::c_int>(
                child_entry_point::<F, R> as *const (),
            ),
            stack_top as *mut libc::c_void,
            clone_flags,
            payload_ptr as *mut libc::c_void,
        )
    };

    if child_pid < 0 {
        return Err(IsolationError::ProcessFailure(format!(
            "Failed to clone execution layer: errno {}",
            std::io::Error::last_os_error()
        )));
    }

    let pid = Pid::from_raw(child_pid);

    // Coordinate with child across synchronization boundary: the readiness frame carries the
    // isolated network namespace's mock listener descriptor when a network boundary is configured.
    let (ready_byte, forwarded_listener) = recv_boundary_ready(parent_sock.as_raw_fd());

    // Serve the forwarded listener on the control plane. The listener stays bound inside the
    // isolated network namespace, so connections originating there reach this proxy.
    let network = match (forwarded_listener, config.network_boundary.as_ref()) {
        (Some(forwarded), Some(boundary)) => {
            let listener = unsafe { TcpListener::from_raw_fd(forwarded.into_raw_fd()) };
            match TransparentProxy::from_listener(listener, boundary.schema.clone()) {
                Ok(proxy) => Some(proxy),
                Err(e) => {
                    terminate_child(pid);
                    return Err(IsolationError::DeltaError(e));
                }
            }
        }
        (Some(_), None) => {
            terminate_child(pid);
            return Err(IsolationError::SyncError(
                "Received an unexpected network boundary listener from the isolated execution layer"
                    .to_string(),
            ));
        }
        (None, _) => None,
    };

    if ready_byte == BOUNDARY_READY {
        // Reset kernel page-table tracking for child: write "4\n" to /proc/[pid]/clear_refs
        let clear_refs_path = format!("/proc/{}/clear_refs", child_pid);
        if let Ok(mut file) = std::fs::File::create(&clear_refs_path) {
            use std::io::Write;
            let _ = file.write_all(b"4\n");
        }

        // Send ACK byte to release child into action execution
        send_control_byte(parent_sock.as_raw_fd(), 1);
    }

    // Await the completion frame: a boundary breach record or a clean-completion marker
    let mut tag = [0u8; 1];
    let tag_len = unsafe {
        libc::read(
            parent_sock.as_raw_fd(),
            tag.as_mut_ptr() as *mut libc::c_void,
            1,
        )
    };

    if tag_len != 1 {
        // Execution layer terminated before reporting; decode the raw wait status
        let wait_status = waitpid(pid, None).map_err(|e| {
            IsolationError::ProcessFailure(format!("waitpid failure on child {child_pid}: {e}"))
        })?;
        return Ok((decode_wait_status(wait_status), None));
    }

    if tag[0] == BOUNDARY_VIOLATION {
        let mut packet = ViolationPacket {
            syscall_nr: 0,
            instruction_pointer: 0,
        };
        let packet_bytes = unsafe {
            std::slice::from_raw_parts_mut(
                &mut packet as *mut ViolationPacket as *mut u8,
                VIOLATION_PACKET_SIZE,
            )
        };

        let mut received = 0usize;
        while received < VIOLATION_PACKET_SIZE {
            let n = unsafe {
                libc::read(
                    parent_sock.as_raw_fd(),
                    packet_bytes[received..].as_mut_ptr() as *mut libc::c_void,
                    VIOLATION_PACKET_SIZE - received,
                )
            };
            if n <= 0 {
                break;
            }
            received += n as usize;
        }

        let _ = waitpid(pid, None);

        let status = if received == VIOLATION_PACKET_SIZE && packet.syscall_nr != 0 {
            BoundaryExitStatus::SyscallViolation {
                syscall_nr: packet.syscall_nr,
                instruction_pointer: packet.instruction_pointer,
            }
        } else {
            BoundaryExitStatus::SyscallViolation {
                syscall_nr: 0,
                instruction_pointer: 0,
            }
        };

        return Ok((status, None));
    }

    // Clean completion: the address space and network boundary are live until released
    let inspection = inspect(BoundaryContext { child_pid, network });

    send_control_byte(parent_sock.as_raw_fd(), 1);

    let wait_status = waitpid(pid, None).map_err(|e| {
        IsolationError::ProcessFailure(format!("waitpid failure on child {child_pid}: {e}"))
    })?;

    Ok((decode_wait_status(wait_status), Some(inspection)))
}
